// Generated by delombok at Tue Sep 03 11:12:20 CEST 2019
// Copyright (c) 2018, Yubico AB
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//
// 1. Redistributions of source code must retain the above copyright notice, this
//    list of conditions and the following disclaimer.
//
// 2. Redistributions in binary form must reproduce the above copyright notice,
//    this list of conditions and the following disclaimer in the documentation
//    and/or other materials provided with the distribution.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
// DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
// FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
// DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
// SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
// CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
// OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
package ssido.core.data;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import ssido.util.CollectionUtil;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nonnull;

/**
 * The PublicKeyCredentialRequestOptions dictionary supplies get() with the data it needs to generate an assertion.
 * <p>
 * Its challenge member must be present, while its other members are optional.
 * </p>
 *
 * @see <a href="https://www.w3.org/TR/webauthn/#dictdef-publickeycredentialrequestoptions">§5.5.
 * Options for Assertion Generation (dictionary PublicKeyCredentialRequestOptions)
 * </a>
 */
public final class PublicKeyCredentialRequestOptions {
    /**
     * A challenge that the selected authenticator signs, along with other data, when producing an authentication
     * assertion. See the <a href="https://www.w3.org/TR/webauthn/#cryptographic-challenges">§13.1
     * Cryptographic Challenges</a> security consideration.
     */
    @Nonnull
    private final ByteArray challenge;
    /**
     * Specifies a time, in milliseconds, that the caller is willing to wait for the call to complete.
     * <p>
     * This is treated as a hint, and MAY be overridden by the client.
     * </p>
     */
    @Nonnull
    private final Optional<Long> timeout;
    /**
     * Specifies the relying party identifier claimed by the caller.
     * <p>
     * If omitted, its value will be set by the client.
     * </p>
     */
    @Nonnull
    private final Optional<String> rpId;
    /**
     * A list of {@link PublicKeyCredentialDescriptor} objects representing public key credentials acceptable to the
     * caller, in descending order of the caller’s preference (the first item in the list is the most preferred
     * credential, and so on down the list).
     */
    @Nonnull
    private final Optional<List<PublicKeyCredentialDescriptor>> allowCredentials;
    /**
     * Describes the Relying Party's requirements regarding <a href="https://www.w3.org/TR/webauthn/#user-verification">user
     * verification</a> for the <code>navigator.credentials.get()</code> operation.
     * <p>
     * Eligible authenticators are filtered to only those capable of satisfying this requirement.
     * </p>
     */
    @Nonnull
    private final UserVerificationRequirement userVerification;
    /**
     * Additional parameters requesting additional processing by the client and authenticator.
     * <p>
     * For example, if transaction confirmation is sought from the user, then the prompt string might be included as an
     * extension.
     * </p>
     */
    @Nonnull
    private final AssertionExtensionInputs extensions;

    private PublicKeyCredentialRequestOptions(
            @Nonnull ByteArray challenge, 
            @Nonnull Optional<Long> timeout, 
            @Nonnull Optional<String> rpId, 
            @Nonnull Optional<List<PublicKeyCredentialDescriptor>> allowCredentials, 
            @Nonnull UserVerificationRequirement userVerification, 
            @Nonnull AssertionExtensionInputs extensions) {
        this.challenge = challenge;
        this.timeout = timeout;
        this.rpId = rpId;
        this.allowCredentials = allowCredentials.map(CollectionUtil::immutableList);
        this.userVerification = userVerification;
        this.extensions = extensions;
    }

    @JsonCreator
    private PublicKeyCredentialRequestOptions(
            @Nonnull @JsonProperty("challenge") ByteArray challenge, 
            @JsonProperty("timeout") Long timeout, 
            @JsonProperty("rpId") String rpId, 
            @JsonProperty("allowCredentials") List<PublicKeyCredentialDescriptor> allowCredentials, 
            @Nonnull @JsonProperty("userVerification") UserVerificationRequirement userVerification, 
            @JsonProperty("extensions") AssertionExtensionInputs extensions) {
        this(challenge, Optional.ofNullable(timeout), Optional.ofNullable(rpId), Optional.ofNullable(allowCredentials), userVerification, Optional.ofNullable(extensions).orElseGet(() -> AssertionExtensionInputs.builder().build()));
    }

    public static PublicKeyCredentialRequestOptionsBuilder.MandatoryStages builder() {
        return new PublicKeyCredentialRequestOptionsBuilder.MandatoryStages();
    }


    public static class PublicKeyCredentialRequestOptionsBuilder {
        private ByteArray challenge;
        private UserVerificationRequirement userVerification = UserVerificationRequirement.PREFERRED;
        private AssertionExtensionInputs extensions = AssertionExtensionInputs.builder().build();
        @Nonnull
        private Optional<Long> timeout = Optional.empty();
        @Nonnull
        private Optional<String> rpId = Optional.empty();
        @Nonnull
        private Optional<List<PublicKeyCredentialDescriptor>> allowCredentials = Optional.empty();


        public static class MandatoryStages {
            private PublicKeyCredentialRequestOptionsBuilder builder = new PublicKeyCredentialRequestOptionsBuilder();

            public PublicKeyCredentialRequestOptionsBuilder challenge(ByteArray challenge) {
                return builder.challenge(challenge);
            }
        }

        /**
         * Specifies a time, in milliseconds, that the caller is willing to wait for the call to complete.
         * <p>
         * This is treated as a hint, and MAY be overridden by the client.
         * </p>
         * @param timeout
         * @return 
         */
        public PublicKeyCredentialRequestOptionsBuilder timeout(@Nonnull Optional<Long> timeout) {
            this.timeout = timeout;
            return this;
        }

        /**
         * Specifies a time, in milliseconds, that the caller is willing to wait for the call to complete.
         * <p>
         * This is treated as a hint, and MAY be overridden by the client.
         * </p>
         * @param timeout
         * @return 
         */
        public PublicKeyCredentialRequestOptionsBuilder timeout(long timeout) {
            return this.timeout(Optional.of(timeout));
        }

        /**
         * Specifies the relying party identifier claimed by the caller.
         * <p>
         * If omitted, its value will be set by the client.
         * </p>
         * @param rpId
         * @return 
         */
        public PublicKeyCredentialRequestOptionsBuilder rpId(@Nonnull Optional<String> rpId) {
            this.rpId = rpId;
            return this;
        }

        /**
         * Specifies the relying party identifier claimed by the caller.
         * <p>
         * If omitted, its value will be set by the client.
         * </p>
         * @param rpId
         * @return 
         */
        public PublicKeyCredentialRequestOptionsBuilder rpId(@Nonnull String rpId) {
            return this.rpId(Optional.of(rpId));
        }

        /**
         * A list of {@link PublicKeyCredentialDescriptor} objects representing public key credentials acceptable to the
         * caller, in descending order of the caller’s preference (the first item in the list is the most preferred
         * credential, and so on down the list).
         * @param allowCredentials
         * @return 
         */
        public PublicKeyCredentialRequestOptionsBuilder allowCredentials(@Nonnull Optional<List<PublicKeyCredentialDescriptor>> allowCredentials) {
            this.allowCredentials = allowCredentials;
            return this;
        }

        /**
         * A list of {@link PublicKeyCredentialDescriptor} objects representing public key credentials acceptable to the
         * caller, in descending order of the caller’s preference (the first item in the list is the most preferred
         * credential, and so on down the list).
         * @param allowCredentials
         * @return 
         */
        public PublicKeyCredentialRequestOptionsBuilder allowCredentials(@Nonnull List<PublicKeyCredentialDescriptor> allowCredentials) {
            return this.allowCredentials(Optional.of(allowCredentials));
        }

        PublicKeyCredentialRequestOptionsBuilder() {
        }

        /**
         * A challenge that the selected authenticator signs, along with other data, when producing an authentication

         * assertion. See the <a href="https://www.w3.org/TR/webauthn/#cryptographic-challenges">§13.1
         * Cryptographic Challenges</a> security consideration.
         * @param challenge
         * @return 
         */
        public PublicKeyCredentialRequestOptionsBuilder challenge(@Nonnull final ByteArray challenge) {
            this.challenge = challenge;
            return this;
        }

        /**
         * Describes the Relying Party's requirements regarding <a href="https://www.w3.org/TR/webauthn/#user-verification">user
         * verification</a> for the <code>navigator.credentials.get()</code> operation.
         * <p>
         * Eligible authenticators are filtered to only those capable of satisfying this requirement.
         * </p>
         * @param userVerification
         * @return 
         */
        public PublicKeyCredentialRequestOptionsBuilder userVerification(@Nonnull final UserVerificationRequirement userVerification) {
            this.userVerification = userVerification;
            return this;
        }

        /**
         * Additional parameters requesting additional processing by the client and authenticator.
         * <p>
         * For example, if transaction confirmation is sought from the user, then the prompt string might be included as an
         * extension.
         * </p>
         * @param extensions
         * @return 
         */
        public PublicKeyCredentialRequestOptionsBuilder extensions(@Nonnull final AssertionExtensionInputs extensions) {
            this.extensions = extensions;
            return this;
        }

        public PublicKeyCredentialRequestOptions build() {
            return new PublicKeyCredentialRequestOptions(challenge, timeout, rpId, allowCredentials, userVerification, extensions);
        }
    }

    public PublicKeyCredentialRequestOptionsBuilder toBuilder() {
        return new PublicKeyCredentialRequestOptionsBuilder().challenge(this.challenge).timeout(this.timeout).rpId(this.rpId).allowCredentials(this.allowCredentials).userVerification(this.userVerification).extensions(this.extensions);
    }

    /**
     * A challenge that the selected authenticator signs, along with other data, when producing an authentication
     * assertion. See the <a href="https://www.w3.org/TR/webauthn/#cryptographic-challenges">§13.1
     * Cryptographic Challenges</a> security consideration.
     * @return 
     */
    @Nonnull
    public ByteArray getChallenge() {
        return this.challenge;
    }

    /**
     * Specifies a time, in milliseconds, that the caller is willing to wait for the call to complete.
     * <p>
     * This is treated as a hint, and MAY be overridden by the client.
     * </p>
     * @return 
     */
    @Nonnull
    public Optional<Long> getTimeout() {
        return this.timeout;
    }

    /**
     * Specifies the relying party identifier claimed by the caller.
     * <p>
     * If omitted, its value will be set by the client.
     * </p>
     * @return 
     */
    @Nonnull
    public Optional<String> getRpId() {
        return this.rpId;
    }

    /**
     * A list of {@link PublicKeyCredentialDescriptor} objects representing public key credentials acceptable to the
     * caller, in descending order of the caller’s preference (the first item in the list is the most preferred
     * credential, and so on down the list).
     * @return 
     */
    @Nonnull
    public Optional<List<PublicKeyCredentialDescriptor>> getAllowCredentials() {
        return this.allowCredentials;
    }

    /**
     * Describes the Relying Party's requirements regarding <a href="https://www.w3.org/TR/webauthn/#user-verification">user
     * verification</a> for the <code>navigator.credentials.get()</code> operation.
     * <p>
     * Eligible authenticators are filtered to only those capable of satisfying this requirement.
     * </p>
     * @return 
     */
    @Nonnull
    public UserVerificationRequirement getUserVerification() {
        return this.userVerification;
    }

    /**
     * Additional parameters requesting additional processing by the client and authenticator.
     * <p>
     * For example, if transaction confirmation is sought from the user, then the prompt string might be included as an
     * extension.
     * </p>
     * @return 
     */
    @Nonnull
    public AssertionExtensionInputs getExtensions() {
        return this.extensions;
    }
}
