// Generated by delombok at Tue Sep 03 11:12:20 CEST 2019
// Copyright (c) 2018, Yubico AB
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//
// 1. Redistributions of source code must retain the above copyright notice, this
//    list of conditions and the following disclaimer.
//
// 2. Redistributions in binary form must reproduce the above copyright notice,
//    this list of conditions and the following disclaimer in the documentation
//    and/or other materials provided with the distribution.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
// DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
// FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
// DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
// SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
// CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
// OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
package ssido.core.meta;

import java.net.URL;
import java.util.Optional;

/**
 * Description of this version of this library
 */
public final class Implementation {
    /**
     * The version number of this release of the library.
     */
    private final Optional<String> version;
    /**
     * Address to where the source code for this library can be found.
     */
    private final URL sourceCodeUrl;

    /**
     * The version number of this release of the library.
     * @return 
     */
    public Optional<String> getVersion() {
        return this.version;
    }

    /**
     * Address to where the source code for this library can be found.
     * @return 
     */
    public URL getSourceCodeUrl() {
        return this.sourceCodeUrl;
    }

   

    @Override
    public String toString() {
        return "Implementation(version=" + this.getVersion() + ", sourceCodeUrl=" + this.getSourceCodeUrl() + ")";
    }

    Implementation(final Optional<String> version, final URL sourceCodeUrl) {
        this.version = version;
        this.sourceCodeUrl = sourceCodeUrl;
    }
}
